### ISSUE TITLE
Too many items with the same position on one axis. Bucket size must be increased to at least 1 more than the number of items with the same position on one axis.

### ISSUE THREAD

**Issue by SantEnnio** [ArthurBrussee/brush#71]
Hi! I'm trying to train a synthetic dataset exported from Blender, and I get this.

```
2024-12-20 19:10:47.157 brush_app[36591:1267327] +[IMKInputSession subclass]: chose IMKInputSession_Modern
thread 'tokio-runtime-worker' panicked at /Users/enniopirolo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kiddo-4.2.1/src/float/construction.rs:223:25:
Too many items with the same position on one axis. Bucket size must be increased to at least 1 more than the number of items with the same position on one axis.
```

I'm not proficient in Rust, so I struggle with reading the code. What's the error about, and how can I increase the bucket size? 

Thanks!

**Comment by ArthurBrussee** [comment]
Ah strange error! When initializing, the scales of the splats are based on how close their nearest neighbours are. I use a libray to this and it's complaining that SO many points are close to each other it can't make sense of it.

I'll try to up some of these limits but, it is a bit suspicious - do you have a sense of how big / how dense the initialization is? Maybe it's being read in incorrectly? If you're comfortable sharing the data that could help debugging!

**Comment by ArthurBrussee** [comment]
Ok I actually ran into this myself with a dataset - kiddo (KNN library I used) has an odd limitation that only some number of points can lay on the same axis - and that number has to be decided at compile time!

Kiddo is a bit overengineered so I've gone ahead and replaced it with a smaller dependency https://github.com/ArthurBrussee/brush/commit/517137275e0305e55c979104869f443811e1a50c

Fixed my scan so hopefully for you too!

**Comment by SantEnnio** [comment]
Thanks for taking the time to check it, and I'm sorry for my late reply.

The error is not present anymore, but the dataset is still not read by brush. There's something I'm missing from the data structure for sure. Here's the dataset:

https://drive.google.com/drive/folders/15x_U8Dv1YIZSHJTupCGELShrFftSYjoz?usp=sharing

Maybe it's the case to move the discussion to Discord?

**Comment by SantEnnio** [comment]
Just to update you, I solved my issue, I don't know if it was a problem with the generated datasets or the latest updates of the repo. Thanks!

**Comment by ArthurBrussee** [comment]
Thanks for giving it another shot! I think there is some weird stuff going on with the dataset though :) One of the zips didn't load. More worryingly:

- The initial ply wasn't used, it had to be named init.ply for things to work. Instead, I've made things more flexible so if there's one ply file exactly in a dataset it now uses that. Better init should help a lot!
- The file format doesn't seem to 100% match the nerfstudio format... specifically, it specified fl_x & fl_y (focal length x & y) but ALSO a camera angle x and y. Those should agree but in this dataset don't match... camera_angle_x & y are independent of resolution so less error prone - I've changed the code to prefer those. Was this dataset created in a specific way? Maybe I am missing something.
- Not really an error, but, in the original format there was transforms_train, transforms_val and transforms_test. I used _val for an eval scene, and kind of discareded _test. I now use _test as eval if there is no _val, so you actually get some eval PSNR numbers. Except that err _test is empty as well in this dataset haha, but nice to know what formats people use!

Lastly, you'll have to fix this one, but there are some training images where the camera is sort of "clipping" the ground plane, which can't really be represented! That messes with training slightly.

After those fixes training seems to work ok on that dataset:
<img width="1232" alt="image" src="https://github.com/user-attachments/assets/10159a12-50fa-47ee-b99f-701ff59093f5" />

For a synthetic dataset like this setting a grey background (or having transparnt input images) would really help, but

Lmk if you run into other trouble!

**Comment by SantEnnio** [comment]
Thanks again! I am testing it right now, and it works way better, even on the first training steps. 

Btw, to add more info. 
I'm using data exported from this plugin:
https://blendermarket.com/products/splatman?search_id=35428105
but with my company, I have plans to create exporters for synthetic data on various platforms.
I also have developed a Blender plugin for photogrammetry on MacOS as a little side-project, this:
https://blendermarket.com/products/snapmesh-blender-photogrammetry-workflow-for-mac-os
and my idea is to add the export of camera poses & point clouds from the plugin to a format usable in Brush, maybe call directly the training from the cli? 

Maybe after these developments, it would be cool to add a macOS-only integration to Brush to use the Object Capture APIs to get camera poses and the sparse point cloud, it would be cool to contribute to the project :)
